### ISSUE TITLE
fail to run

### ISSUE THREAD

**Issue by wizard-gg** [NarSiiiS/rj-downloader#5]
hi i run project with npx next dev and got this error blow:

`error - FetchError: invalid json response body at http://rj.wiz.gg/home reason: Unexpected token < in JSON at position 0
    at /www/wwwroot/rj-downloader/node_modules/next/dist/compiled/node-fetch/index.js:1:51227
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getServerSideProps (webpack-internal:///./src/pages/index.tsx:76:22)
    at async Object.renderToHTML (/www/wwwroot/rj-downloader/node_modules/next/dist/server/render.js:490:20)
    at async doRender (/www/wwwroot/rj-downloader/node_modules/next/dist/server/base-server.js:908:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/www/wwwroot/rj-downloader/node_modules/next/dist/server/base-server.js:1013:28)
    at async /www/wwwroot/rj-downloader/node_modules/next/dist/server/response-cache.js:69:36 {
  type: 'invalid-json',
  page: '/'
}`

ubuntu 20.04

**Comment by NarSiiiS** [comment]
You need correct api address in env :
`NEXT_PUBLIC_BASE_URL=https://rj-api.vercel.app`
